### ISSUE TITLE
keytar / gyp error

### ISSUE THREAD

**Issue by tangentsoft** [headmelted/codebuilds#116]
I'm not sure if this is one error or two:

```
error /usr/local/src/codebuilds/code/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /usr/local/src/codebuilds/code/node_modules/keytar
Output:
/usr/local/src/codebuilds/code/node_modules/node-abi/index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 8.3.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/usr/local/src/codebuilds/code/node_modules/node-abi/index.js:30:9)
    at module.exports (/usr/local/src/codebuilds/code/node_modules/prebuild-install/rc.js:73:57)
    at Object.<anonymous> (/usr/local/src/codebuilds/code/node_modules/prebuild-install/bin.js:9:25)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

I'm getting that on an AMD64 Chromebook running Debian Buster under the beta Linux container feature.

**Comment by MathieuDSTP** [comment]
I get the same error on Manjaro on ARM64 (Pinebook Pro).
