### ISSUE TITLE
Longing for aarch64 support :)

### ISSUE THREAD

**Issue by brusan** [headmelted/codebuilds#47]
Hi,
Trying to install VS Code on a Rock64 fails. Any prognosis for when it can be fixed - or even better: can I be of any help? 

Error on install:
Done!
Installing Visual Studio Code...
aarch64 currently disabled. THIS IS BEING WORKED ON, APOLOGIES FOR THE INCONVENIENCE, PLEASE CHECK https://code.headmelted.com FOR UPDATES
rock64@rock64:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Br /Brusan

**Comment by chozar** [comment]
I have an aarch64 chromebook and was getting the same error.

chromebook.sh correctly installs crouton, which calls an apt.sh installation script as part of it that installs vss.  Take a look at chromebook.sh and find:

https://code.headmelted.com/installers/apt.sh

Grab that script with wget, and take a look, there's a section that checks if arch = aarch64, and exits.  I just commented that entire block out, and reran apt.sh, and it installs and works just fine.  Based on other comments with install scripts I had the feeling that 32 bit arm should work just fine on 64, but for some reason uname is saying it's aarch64 even in a chroot set up as armhf.

I went back and made the alias manually, as that part of the chromebook.sh never was reached.

I really appreciate the work in creating this package, but I think it could be useful to publish some lower level directions for people that have some crouton experience.  Simply the repo to add and the apt commands to install vss.

I could be completely mistaken too, as I've not really used VSS on chromebook too much yet.  For all I know it fails miserably with any real usage, and that error warning is valid.

**Comment by brusan** [comment]
Thank you for your input, chozar. I'll take a look at the script and see if I can work something out.

**Comment by acruzpr** [comment]
@chozar  It will keep saying aarch64 because chroot is using the Chromebook Linux kernel at least that's the case in my armhf Chromebook.

@biancashouse  Your Chromebook is aarch64 too? If that's the case then vscode is not been installed on your computer because there is no package for the aarch64 architecture.
One line of the script install a repository where all the packages reside and the repository depends on the architecture.

You could try to compile vscode your self, is really easy. There is a page with instructions on how to compile it on the Rpi 3 (aarch64).

**Comment by magic-k** [comment]
The easiest way is to use a armhf (32bit) chroot. And as this package is very old, take one from https://github.com/stevedesmond-ca/vscode-arm which is at least at 1.21.1. VScode is in the process of adopting electron 2.0. From there, ARM-Support, especially aarch64 support,  should be much easier to integrate into the build process of vscode.

**Comment by magic-k** [comment]
AFAIK you can start a container with armhf. On https://www.reddit.com/r/Crostini/ i saw people running vscode on the cb+

**Comment by mattocchi** [comment]
On Acer Chromebook R13 aarch64 I'm able to run armhf vscode
I assume your setup is halted running apt.sh at "aarch64 currently disabled..."
Now enter on chrooted dist installed with : sudo enter-chroot -n code-oss-chroot
1) manually added headmelted repo (as you ca see on apt.sh)
2) manually installed code-oss armhf: sudo apt-get install code-oss
3) add this package (I do not know if all dependecies are necessary, but trying to manually compiling vscode I saw that with this package code-oss run well: sudo apt-get install libibus-1.0-dev
4) exit from chroot
5) enjoy: sudo startxiwi -n code-oss-chroot code-oss
I suppose it is also possibile to run entire chrooted armhf dist

**Comment by headmelted** [comment]
hi all, I've picked this up again. I'm expecting to have arm64 builds soon (as in days, rather than weeks or months).

I would expect that anyone who has an arm64 Chromebook would be better off installing the application inside Crostini (i.e. Chrome OS' native linux support, as discussed above) as the experience will just plain be better.

For 32-bit arm the process will stay much as is (Google don't have plans to bring Linux to 32-bit ARM devices sadly).

**Comment by magic-k** [comment]
There are only a few arm64 chromebooks with crostini enabled and only in dev or beta channel. So i guess the majority, like me with my R13,  will still use crouton. I appreciate that you picked it up again and kudos to microsoft to finally accept the changes. Building it on my CB was an interesting experience, learned a lot but i have no problems getting rid of the repo and start to download debs again :-)

**Comment by headmelted** [comment]
I have the build system kicking out new DEBs again, so later this evening I'll try to get testing the scripts with my Chromebook Flip C100PA (Non-Crostini, armhf - so the same basic architecture as your R13).

I understand some changes to the underlying linux have meant that the scripts aren't working on the latest Chrome OS builds, so if that's the case I'll get them patched up - hopefully tonight 👍

**Comment by magic-k** [comment]
The R13 is aarch64, not armhf.

**Comment by headmelted** [comment]
In that case, mind testing this for me?

https://packagecloud.io/headmelted/codebuilds/packages/ubuntu/xenial/code-oss_1.28.0-1536678946_arm64.deb/download.deb

It may bounce you around a bit first.

**Comment by magic-k** [comment]
My CB is at home. I can test it this evening.

**Comment by magic-k** [comment]
Something seems to go wrong. I get an empty window. This is in the log:
```
[main 19:30:08] windowsManager#open
[23924:0912/193010.969082:INFO:CONSOLE(249)] "Loading "node-pty" failed", source: /usr/share/code-oss/resources/app/out/vs/loader.js (249)
[23924:0912/193010.969652:INFO:CONSOLE(250)] "Detail: ", source: /usr/share/code-oss/resources/app/out/vs/loader.js (250)
[23924:0912/193010.969992:INFO:CONSOLE(252)] "Error: /usr/share/code-oss/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/share/code-oss/resources/app/out/vs/loader.js:686:36)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:252:3)
    at Module.NodeScriptLoader._initNodeRequire.Module._compile (/usr/share/code-oss/resources/app/out/vs/loader.js:718:45)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/share/code-oss/resources/app/out/vs/loader.js:686:36)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/index.js:13:20)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/index.js:50:3)
    at Module.NodeScriptLoader._initNodeRequire.Module._compile (/usr/share/code-oss/resources/app/out/vs/loader.js:718:45)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at nodeRequire (/usr/share/code-oss/resources/app/out/vs/loader.js:1678:32)
    at NodeScriptLoader.load (/usr/share/code-oss/resources/app/out/vs/loader.js:735:39)
    at OnlyOnceScriptLoader.load (/usr/share/code-oss/resources/app/out/vs/loader.js:581:32)
    at loadNextPath (/usr/share/code-oss/resources/app/out/vs/loader.js:1441:41)
    at Object.errorback (/usr/share/code-oss/resources/app/out/vs/loader.js:1449:25)
    at OnlyOnceScriptLoader.triggerErrorback (/usr/share/code-oss/resources/app/out/vs/loader.js:594:36)
    at /usr/share/code-oss/resources/app/out/vs/loader.js:581:151
    at ReadFileContext.callback (/usr/share/code-oss/resources/app/out/vs/loader.js:748:25)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)", source: /usr/share/code-oss/resources/app/out/vs/loader.js (252)
[23924:0912/193010.970581:INFO:CONSOLE(254)] "Here are the modules that depend on it:", source: /usr/share/code-oss/resources/app/out/vs/loader.js (254)
[23924:0912/193010.970837:INFO:CONSOLE(255)] "vs/workbench/parts/terminal/node/terminalProcess", source: /usr/share/code-oss/resources/app/out/vs/loader.js (255)
[23924:0912/193013.137092:INFO:CONSOLE(13847)] "Error: /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (13847)
[23924:0912/193013.144137:INFO:CONSOLE(13847)] "Error: /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (13847)
[main 19:30:18] Lifecycle#window-before-close 1
[main 19:30:18] Lifecycle#onBeforeWindowClose.fire()
[main 19:30:18] Lifecycle#window-before-close 1
[main 19:30:18] Lifecycle#window-close 1
[main 19:30:18] Lifecycle#window-closed 1
[main 19:30:18] Lifecycle#onShutdown.fire()
[main 19:30:18] Lifecycle#window-all-closed
[main 19:30:18] Lifecycle#before-quit
[main 19:30:18] Lifecycle#onBeforeShutdown.fire()
[main 19:30:18] App#will-quit: disposing resources

```

**Comment by magic-k** [comment]
The german messages mean "File not found". Which node version are you using?

**Comment by headmelted** [comment]
8.9.0 - is there an issue with that version?

**Comment by magic-k** [comment]
According to https://github.com/Microsoft/vscode/wiki/How-to-Contribute it should be:
Node.JS, >= 8.9.1, < 9.0.0

**Comment by headmelted** [comment]
Nice catch!

Updating this now - the CI should kick out a new deb in about 20 minutes.

**Comment by headmelted** [comment]
https://packagecloud.io/headmelted/codebuilds/packages/ubuntu/xenial/code-oss_1.28.0-1536904620_arm64.deb

Try this one. If it doesn't work please send me the logs again and I'll investigate the node-pty issues.

**Comment by magic-k** [comment]
No, still empty window. Error log looks a bit different though.
`[main 20:48:49] windowsManager#open
[22967:0914/204853.373453:INFO:CONSOLE(13852)] "Error: /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (13852)
[22967:0914/204853.377851:INFO:CONSOLE(13852)] "Error: /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (13852)
[22967:0914/204853.593058:INFO:CONSOLE(249)] "Loading "node-pty" failed", source: /usr/share/code-oss/resources/app/out/vs/loader.js (249)
[22967:0914/204853.593134:INFO:CONSOLE(250)] "Detail: ", source: /usr/share/code-oss/resources/app/out/vs/loader.js (250)
[22967:0914/204853.594839:INFO:CONSOLE(252)] "Error: /usr/share/code-oss/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/share/code-oss/resources/app/out/vs/loader.js:686:36)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:252:3)
    at Module.NodeScriptLoader._initNodeRequire.Module._compile (/usr/share/code-oss/resources/app/out/vs/loader.js:718:45)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/share/code-oss/resources/app/out/vs/loader.js:686:36)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/index.js:13:20)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/node-pty/lib/index.js:50:3)
    at Module.NodeScriptLoader._initNodeRequire.Module._compile (/usr/share/code-oss/resources/app/out/vs/loader.js:718:45)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at nodeRequire (/usr/share/code-oss/resources/app/out/vs/loader.js:1678:32)
    at NodeScriptLoader.load (/usr/share/code-oss/resources/app/out/vs/loader.js:735:39)
    at OnlyOnceScriptLoader.load (/usr/share/code-oss/resources/app/out/vs/loader.js:581:32)
    at loadNextPath (/usr/share/code-oss/resources/app/out/vs/loader.js:1441:41)
    at Object.errorback (/usr/share/code-oss/resources/app/out/vs/loader.js:1449:25)
    at OnlyOnceScriptLoader.triggerErrorback (/usr/share/code-oss/resources/app/out/vs/loader.js:594:36)
    at /usr/share/code-oss/resources/app/out/vs/loader.js:581:151
    at ReadFileContext.callback (/usr/share/code-oss/resources/app/out/vs/loader.js:748:25)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)", source: /usr/share/code-oss/resources/app/out/vs/loader.js (252)
[22967:0914/204853.595463:INFO:CONSOLE(254)] "Here are the modules that depend on it:", source: /usr/share/code-oss/resources/app/out/vs/loader.js (254)
[22967:0914/204853.595533:INFO:CONSOLE(255)] "vs/workbench/parts/terminal/node/terminalProcess", source: /usr/share/code-oss/resources/app/out/vs/loader.js (255)
`

**Comment by magic-k** [comment]
FYI a native build runs without problems on my chromebook.

**Comment by headmelted** [comment]
I think I've traced it to node-gyp. Pretty sure I can get it patched up but
it could be Monday before I get another build out.

I really appreciate the help with testing btw 🙂

**Comment by unixfox** [comment]
I've the same error as @magic-k on my Pinebook which is internally a Pine64.

**Comment by magic-k** [comment]
Just as an info, the following executables are x86 format in the last build:
```
(bionic64)magick@localhost:~/usr$ find . -type f -exec file {} ";" | grep x86
./share/code-oss/resources/app/extensions/search-rg/node_modules/vscode-ripgrep/bin/rg: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=5882d80bb11d239c7474708c74781e28b384236d, stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=f48d0b31ab2fe4b41ed2db0992a092a2533644f0, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/obj.target/spdlog.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=f48d0b31ab2fe4b41ed2db0992a092a2533644f0, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/oniguruma/build/Release/onig_scanner.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d5fe925605eeca0cf93b599456adf2111e87bbb5, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/oniguruma/build/Release/obj.target/onig_scanner.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d5fe925605eeca0cf93b599456adf2111e87bbb5, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/native-keymap/build/Release/obj.target/keymapping.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=eb2095733d161e81d86d291480f7673987aa1185, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=eb2095733d161e81d86d291480f7673987aa1185, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/native-is-elevated/build/Release/is-elevated.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f40bd3bbb47344bea4b1d7cca1a62b261eff52b0, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/native-is-elevated/build/Release/obj.target/is-elevated.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f40bd3bbb47344bea4b1d7cca1a62b261eff52b0, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/native-watchdog/build/Release/obj.target/watchdog.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=dcb97ddaa967e1069e7415820a0d7c519911ec6d, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/native-watchdog/build/Release/watchdog.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=dcb97ddaa967e1069e7415820a0d7c519911ec6d, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=5882d80bb11d239c7474708c74781e28b384236d, stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/gc-signals/build/Release/obj.target/gcsignals.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=da5068de34aa32edc14e9af10926d31189b010e4, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/gc-signals/build/Release/gcsignals.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=da5068de34aa32edc14e9af10926d31189b010e4, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/vscode-nsfw/build/Release/obj.target/nsfw.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=8dd40c52c937c82af020e920fda752be672db43f, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/vscode-nsfw/build/Release/nsfw.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=8dd40c52c937c82af020e920fda752be672db43f, not stripped
./share/code-oss/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=223fd55a25842dc451d4fa9f48038f4203140744, not stripped

```

**Comment by headmelted** [comment]
Have figured out the issue - which as I'm sure you guessed already is that
the linker is pointing to the wrong arch libs.

Have a fix, just trying to get some issues with compiling on Travis sorted.

Will have new packages asap that will sort this!

**Comment by headmelted** [comment]
Pretty sure this build solves the linking problem:

https://packagecloud.io/headmelted/codebuilds/packages/ubuntu/xenial/code-oss_1.28.0-1537541296_arm64.deb

Please let me know if you're still hitting issues with it :-)

**Comment by magic-k** [comment]
This version works. Thanks.

**Comment by headmelted** [comment]
Thanks for the help with testing!

I'll get the extensions patched back in (Microsoft patch it out in the
source code and add it back in to the official builds, it's not a big deal
to put back). If everyone's satisfied that it's working I'll close the
ticket once this is done.

**Comment by headmelted** [comment]
Closing this one, as the only remaining issue is being tracked in #57.
