### ISSUE TITLE
Problem with Setting Sync 3.2.4 extension

### ISSUE THREAD

**Issue by marcowy** [headmelted/codebuilds#69]
Code-OSS 1.29
Extension: https://github.com/shanalikhan/code-settings-sync

When I try upload or download it should ask for token. Instead of this error occures.

workbench.main.js:290 [Extension Host] Error :/Code - OSS (at new u (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:51:4875))
t.log @ workbench.main.js:290
t._logExtensionHostMessage @ workbench.main.js:3186
(anonymous) @ workbench.main.js:3182
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:290 [Extension Host] Error: ENOENT: no such file or directory, stat '/home/pi/.config/Code - OSS'
	at fs.statSync (fs.js:954:11)
	at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
	at Object.statSync (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:50169)
	at new u (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:51:4808)
	at t.Sync.<anonymous> (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:76613)
	at Generator.next (<anonymous>)
	at /home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:71507
	at new Promise (<anonymous>)
	at n (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:71284)
	at t.Sync.download (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:76572)
	at e._executeContributedCommand (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:461:773)
	at e.$executeContributedCommand (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:462:278)
	at t._doInvokeHandler (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:610:202)
	at t._invokeHandler (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:609:883)
	at t._receiveRequest (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:608:490)
	at t._receiveOneMessage (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:607:412)
	at /usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:605:244
	at /usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:101:635
	at e.fire (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:103:76)
	at a (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:159:1008)
	at Socket._socketDataListener (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:160:212)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) (at new u (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:51:4902))
t.log @ workbench.main.js:290
t._logExtensionHostMessage @ workbench.main.js:3186
(anonymous) @ workbench.main.js:3182
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:290 [Extension Host] Error :/VSCodium (at new u (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:51:4875))
t.log @ workbench.main.js:290
t._logExtensionHostMessage @ workbench.main.js:3186
(anonymous) @ workbench.main.js:3182
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:290 [Extension Host] Error: ENOENT: no such file or directory, stat '/home/pi/.config/VSCodium'
	at fs.statSync (fs.js:954:11)
	at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
	at Object.statSync (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:50169)
	at new u (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:51:4808)
	at t.Sync.<anonymous> (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:76613)
	at Generator.next (<anonymous>)
	at /home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:71507
	at new Promise (<anonymous>)
	at n (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:71284)
	at t.Sync.download (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:76572)
	at e._executeContributedCommand (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:461:773)
	at e.$executeContributedCommand (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:462:278)
	at t._doInvokeHandler (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:610:202)
	at t._invokeHandler (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:609:883)
	at t._receiveRequest (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:608:490)
	at t._receiveOneMessage (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:607:412)
	at /usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:605:244
	at /usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:101:635
	at e.fire (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:103:76)
	at a (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:159:1008)
	at Socket._socketDataListener (/usr/share/code-oss/resources/app/out/vs/workbench/node/extensionHostProcess.js:160:212)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) (at new u (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:51:4902))
t.log @ workbench.main.js:290
t._logExtensionHostMessage @ workbench.main.js:3186
(anonymous) @ workbench.main.js:3182
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:290 [Extension Host] TypeError: Cannot read property 'token' of undefined
	at f.<anonymous> (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:91410)
	at Generator.next (<anonymous>)
	at s (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:87946)
	at <anonymous> (at Function.LogException (/home/pi/.vscode-oss/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:88403))
t.log @ workbench.main.js:290
t._logExtensionHostMessage @ workbench.main.js:3186
(anonymous) @ workbench.main.js:3182
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:2418 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
t.onDidNotificationChange @ workbench.main.js:2418
(anonymous) @ workbench.main.js:2418
e.fire @ workbench.main.js:180
t.notify @ workbench.main.js:2474
t.notify @ workbench.main.js:3539
e._showMessage @ workbench.main.js:3255
e._showMessage @ workbench.main.js:3254
e.$showMessage @ workbench.main.js:3254
t._doInvokeHandler @ workbench.main.js:3289
t._invokeHandler @ workbench.main.js:3288
t._receiveRequest @ workbench.main.js:3287
t._receiveOneMessage @ workbench.main.js:3286
(anonymous) @ workbench.main.js:3284
e.fire @ workbench.main.js:180
a @ workbench.main.js:332
n._socketDataListener @ workbench.main.js:332
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594

**Comment by ibuky** [comment]
code-oss ver. 1.32.0 on Chromebook C101PA (arm64)

I had same problem as no directory named 'Code - OSS'.

I solved make symlink named 'Code - OSS' to 'Code - OSS (headmelted)'.
In my environment, generated oss-code directory in `~/.config` is named `Code - OSS (headmelted)`, but the extension refers `Code - OSS` directory only to fail.

below command executed:

```
$ cd ~/.config
$ ln -s 'Code - OSS (headmelted)' 'Code - OSS'
$ ls -la
'Code - OSS' -> 'Code - OSS (headmelted)/'
'Code - OSS (headmelted)'
....
```

**Comment by billyjacoby** [comment]
Just wanted to contribute here, I ran into the same issue and after making the suggested change I was still unable to install any plugins from my settings.

I ended up having to create one more symlink:
`$ cd /user/share/code-oss/bin`
`$ sudo ln -s code-oss code `
